FROM node:18-alpine AS builder

WORKDIR /app

# Installer les dépendances
COPY frontend/package*.json ./
RUN npm install

# Copier le code
COPY frontend ./

# Build de la partie frontend
RUN npm run build

# Étape finale pour servir l'app
FROM node:18-alpine
WORKDIR /app

COPY --from=builder /app ./

EXPOSE 3000
CMD ["npm", "start"]

